/*
  E -> C D
  D -> I A V
  I -> L R
  L -> a..z
  R -> LR | ε
  A -> on
  C -> create index
  V -> I P
  P -> (I)

  tabla:
  E, create index: E -> C D
  D, a..z: D -> I A V
  I, a..z: I -> L R
  L, a..z: L -> a..z
  R, a..z: R -> LR
  R, ε: R -> ε
  A, on: A -> on
  C, create index: C -> create index
  V, a..z: V -> I P
  P, (: P -> (I)
*/

let tokensTerminales = new Set([
  "create index",
  "on",
  "(",
  ")",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "$",
]);

let tabla = {
  E: {
    "create index": ["C", "D"],
  },
  D: {
    a: ["I", "A", "V"],
    b: ["I", "A", "V"],
    c: ["I", "A", "V"],
    d: ["I", "A", "V"],
    e: ["I", "A", "V"],
    f: ["I", "A", "V"],
    g: ["I", "A", "V"],
    h: ["I", "A", "V"],
    i: ["I", "A", "V"],
    j: ["I", "A", "V"],
    k: ["I", "A", "V"],
    l: ["I", "A", "V"],
    m: ["I", "A", "V"],
    n: ["I", "A", "V"],
    o: ["I", "A", "V"],
    p: ["I", "A", "V"],
    q: ["I", "A", "V"],
    r: ["I", "A", "V"],
    s: ["I", "A", "V"],
    t: ["I", "A", "V"],
    u: ["I", "A", "V"],
    v: ["I", "A", "V"],
    w: ["I", "A", "V"],
    x: ["I", "A", "V"],
    y: ["I", "A", "V"],
    z: ["I", "A", "V"],
  },
  I: {
    a: ["L", "R"],
    b: ["L", "R"],
    c: ["L", "R"],
    d: ["L", "R"],
    e: ["L", "R"],
    f: ["L", "R"],
    g: ["L", "R"],
    h: ["L", "R"],
    i: ["L", "R"],
    j: ["L", "R"],
    k: ["L", "R"],
    l: ["L", "R"],
    m: ["L", "R"],
    n: ["L", "R"],
    o: ["L", "R"],
    p: ["L", "R"],
    q: ["L", "R"],
    r: ["L", "R"],
    s: ["L", "R"],
    t: ["L", "R"],
    u: ["L", "R"],
    v: ["L", "R"],
    w: ["L", "R"],
    x: ["L", "R"],
    y: ["L", "R"],
    z: ["L", "R"],
  },
  L: {
    a: ["a"],
    b: ["b"],
    c: ["c"],
    d: ["d"],
    e: ["e"],
    f: ["f"],
    g: ["g"],
    h: ["h"],
    i: ["i"],
    j: ["j"],
    k: ["k"],
    l: ["l"],
    m: ["m"],
    n: ["n"],
    o: ["o"],
    p: ["p"],
    q: ["q"],
    r: ["r"],
    s: ["s"],
    t: ["t"],
    u: ["u"],
    v: ["v"],
    w: ["w"],
    x: ["x"],
    y: ["y"],
    z: ["z"],
  },
  R: {
    a: ["L", "R"],
    b: ["L", "R"],
    c: ["L", "R"],
    d: ["L", "R"],
    e: ["L", "R"],
    f: ["L", "R"],
    g: ["L", "R"],
    h: ["L", "R"],
    i: ["L", "R"],
    j: ["L", "R"],
    k: ["L", "R"],
    l: ["L", "R"],
    m: ["L", "R"],
    n: ["L", "R"],
    o: ["L", "R"],
    p: ["L", "R"],
    q: ["L", "R"],
    r: ["L", "R"],
    s: ["L", "R"],
    t: ["L", "R"],
    u: ["L", "R"],
    v: ["L", "R"],
    w: ["L", "R"],
    x: ["L", "R"],
    y: ["L", "R"],
    z: ["L", "R"],
    "(": [],
    ")" : [],
    "on": [],
  },
  A: {
    "on": ["on"],
  },
  C: {
    "create index": ["create index"],
  },
  V: {
    a: ["I", "P"],
    b: ["I", "P"],
    c: ["I", "P"],
    d: ["I", "P"],
    e: ["I", "P"],
    f: ["I", "P"],
    g: ["I", "P"],
    h: ["I", "P"],
    i: ["I", "P"],
    j: ["I", "P"],
    k: ["I", "P"],
    l: ["I", "P"],
    m: ["I", "P"],
    n: ["I", "P"],
    o: ["I", "P"],
    p: ["I", "P"],
    q: ["I", "P"],
    r: ["I", "P"],
    s: ["I", "P"],
    t: ["I", "P"],
    u: ["I", "P"],
    v: ["I", "P"],
    w: ["I", "P"],
    x: ["I", "P"],
    y: ["I", "P"],
    z: ["I", "P"],
  },
  P: {
    "(": ["(", "I", ")"],
  },
};

export { tabla, tokensTerminales };
